# -*- coding: utf-8 -*-
"""Pizza Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEAmPTzk0YRBPM9fq0s6q2_Ay7zH8cTB

### 🍕 PIZZA SALES ANALYSIS

## Import
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px
warnings.filterwarnings('ignore')

df = pd.read_csv("pizza_sales.csv")

"""## Import report"""

df.head()

df.tail()

print("The Metadata of the data : ",df.shape)

df.shape[0]

df.shape[1]

df.columns

df.dtypes

df.describe()

df.info()

"""## KPI'S"""

total_revenue = df['total_price'].sum()
total_pizzas_sold =df['quantity'].sum()
total_orders = df['order_id'].nunique()
Avg_Order_value = total_revenue/total_orders
avg_pizzas_per_sold = total_pizzas_sold /total_orders

print(f"Total Revenue : $ {total_revenue:,.2f}")
print(f"Total Pizzas Sold : " ,total_pizzas_sold)
print(f"Total Orders : ",total_orders)
print(f"Average Order Value : ",Avg_Order_value)
print(f"Average Pizzas Per Sold : {avg_pizzas_per_sold:,.2f}")

"""## Charts

### 1. Ingredient Analysis
"""

ingredient = (
    df['pizza_ingredients']
    .str.split(',')
    .explode()
    .str.strip()
    .value_counts()
    .reset_index()
    .rename(columns={'index': 'ingredients' , 'pizza_ingredients': 'counts'})
)
print(ingredient.head())

"""### Daily Trend

### Total Orders By Day of the Week
"""

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['day_name'] = df['order_date'].dt.day_name()

weekday_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

df['day_name'] = pd.Categorical(
    df['day_name'],
    categories=weekday_order,
    ordered=True
)

orders_by_day = df.groupby('day_name', observed=False)['order_id'].nunique()

ax = orders_by_day.plot(
    kind='bar',
    figsize=(8,5),
    edgecolor='black'
)

plt.title("Total Orders By Day of the Week")
plt.xlabel("Day of Week")
plt.ylabel("No. of Orders")
plt.xticks(rotation=45)

for i, val in enumerate(orders_by_day):
    plt.text(i, val + 20, str(val),
             ha='center', va='bottom',
             fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""### Total Revenue By Day of the Week"""

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['day_name'] = df['order_date'].dt.day_name()

weekday_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

df['day_name'] = pd.Categorical(
    df['day_name'],
    categories=weekday_order,
    ordered=True
)

orders_by_day = df.groupby('day_name', observed=False)['total_price'].sum()

ax = orders_by_day.plot(
    kind='bar',
    figsize=(8,5),color = 'purple',
    edgecolor='black'
)

plt.title("Total Revenue By Day of the Week")
plt.xlabel("Day of Week")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)

for i, val in enumerate(orders_by_day):
    plt.text(i, val + 20, str(val),
             ha='center', va='bottom',
             fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""### Total Orders By Month"""

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['month_name'] = df['order_date'].dt.month_name()

month_order = [
    "January", "February", "March",
    "April", "May", "June", "July","August","September","October","November","December"
]

df['month_name'] = pd.Categorical(
    df['month_name'],
    categories=month_order,
    ordered=True
)

orders_by_month = df.groupby('month_name', observed=False)['order_id'].nunique()

plt.figure(figsize=(10,5))
plt.fill_between(orders_by_month.index,orders_by_month.values,color = 'orange',alpha = 0.6)
plt.plot(orders_by_month.index,orders_by_month.values,color = 'black',linewidth=2 ,marker = 'o')

plt.title("Total Orders By Month")
plt.xlabel("Month")
plt.ylabel("No. of Orders")
plt.xticks(rotation=45)


for i, val in enumerate(orders_by_month):
    plt.text(i, val + 20, str(val),
             ha='center', va='bottom',
             fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""### Percentage Of sales By Pizza Category"""

category_sales = df.groupby('pizza_category')['total_price'].sum()
category_pct = category_sales / category_sales.sum() * 100
plt.figure(figsize=(7,7))
colors = plt.get_cmap('tab20').colors
plt.pie(category_pct,labels = category_pct.index,autopct = '%1.1f%%',startangle = 90 ,colors = colors,
wedgeprops = {'edgecolor':'black','width':0.4},pctdistance=0.85)
plt.title("Percentage Of sales By Pizza Category")
plt.show()

"""### % sales by pizza size and Category"""

import matplotlib.pyplot as plt
import seaborn as sns

# Pivot table: total sales by category and size
sales_pivot = df.pivot_table(
    index='pizza_category',
    columns='pizza_size',
    values='total_price',
    aggfunc='sum',
    fill_value=0
)

# Convert to percentage row-wise
sales_pct = sales_pivot.div(sales_pivot.sum(axis=1), axis=0) * 100

# Plot heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(
    sales_pct,
    annot=True,       # show numbers
    fmt=".1f",        # format
    cmap="YlOrRd",    # color map
    linewidths=0.5
)

plt.title("Percentage of Sales by Pizza Category & Size")
plt.xlabel("Pizza Size")
plt.ylabel("Pizza Category")
plt.show()

"""### Total pizzas Sold By Pizza Category"""

import matplotlib.pyplot as plt
import seaborn as sns
pizzas_by_category = df.groupby('pizza_category')['quantity'].sum()
colors = list(plt.get_cmap('tab20').colors)
colors = colors [: len(pizzas_by_category)]
ax = pizzas_by_category.plot(kind = 'bar',figsize =(8,5),color = colors,edgecolor='black')
plt.title("Total Pizzas Sold By Pizza Category")
plt.xlabel("Pizza Category")
plt.ylabel("Total Pizzas Sold")
plt.xticks(rotation = 45)
for i ,val in enumerate(pizzas_by_category):
  plt.text(i,val+5 ,str(val),ha = 'center',va='bottom',fontsize =9 ,fontweight = 'bold')
  plt.tight_layout()
  plt.show()

"""### Top 5 Best Selling Pizzas - Total Quantity"""

pizzas_by_name = df.groupby('pizza_name')['quantity'].sum()
top5 = pizzas_by_name.sort_values(ascending= False).head(5)
ax = top5.plot(kind = 'bar',figsize =(8,5),color = 'grey',edgecolor = 'black')
plt.title("Top 5 Pizzas Sold")
plt.xlabel("Pizza Name")
plt.ylabel("Total Pizzas Sold")
plt.xticks(rotation = 45)
for i ,val in enumerate(top5):
  plt.text(i,val+2,str(val),ha='center',va='bottom',fontsize = 9 ,fontweight= 'bold')
  plt.tight_layout()
  plt.show()

"""### Top 5 Best selling pizzas - Total Orders"""

pizzas_by_name = df.groupby('pizza_name')['order_id'].nunique()
top5 = pizzas_by_name.sort_values(ascending= False).head(5)
ax = top5.plot(kind = 'bar',figsize =(9,5),color = 'grey',edgecolor = 'black')
plt.title("Top 5 Pizzas ordered")
plt.xlabel("Pizza Name")
plt.ylabel("Total Pizzas Sold")
plt.xticks(rotation = 45)
for i ,val in enumerate(top5):
  plt.text(i,val+2,str(val),ha='center',va='bottom',fontsize = 9 ,fontweight= 'bold')
  plt.tight_layout()
  plt.show()

"""Top 5 Best selling pizzas - Total Sales"""

pizzas_by_name = df.groupby('pizza_name')['order_id'].nunique()
top5 = pizzas_by_name.sort_values(ascending= False).head(5)
ax = top5.plot(kind = 'bar',figsize =(9,5),color = 'violet',edgecolor = 'black')
plt.title("Top 5 Pizzas by revenue")
plt.xlabel("Pizza Name")
plt.ylabel("Total Pizzas Sold")
plt.xticks(rotation = 45)
for i ,val in enumerate(top5):
  plt.text(i,val+2,str(val),ha='center',va='bottom',fontsize = 9 ,fontweight= 'bold')
  plt.tight_layout()
  plt.show()

"""Bottom 5 Best selling pizzas - Total Sales"""

pizzas_by_name = df.groupby('pizza_name')['order_id'].nunique()
bottom5 = pizzas_by_name.sort_values(ascending= True).head(5)
ax = bottom5.plot(kind = 'bar',figsize =(8,5),color = 'brown',edgecolor = 'black')
plt.title("Bottom 5 Pizzas by sold")
plt.xlabel("Pizza Name")
plt.ylabel("Total Pizzas revenue")
plt.xticks(rotation = 45)
for i ,val in enumerate(top5):
  plt.text(i,val+2,str(val),ha='center',va='bottom',fontsize = 9 ,fontweight= 'bold')
  plt.tight_layout()
  plt.show()